### PR TITLE
AB#3240 - Update documentation

### PR DESCRIPTION
**Pull request by mknoedel**
I included images for the integration walkthrough to help with understanding the issues from Personal and Business MS accounts.

### CODE REVIEW

**Review by ndowmon — APPROVED** [review]

**Comment by austinkelleher** [comment]
Awesome! I love the idea of adding screenshots to docs. Much more useful. A bit more effort to keep up to date as things change, but I think it's worth it from a documentation perspective.

Wondering if we should make these images a bit larger?

https://github.com/JupiterOne/graph-microsoft-365/blob/de8eb28f8d3741249bd53528499460ade7f03e86/docs/jupiterone.md

Screen Shot 2021-02-10 at 2 37 28 PM

**Comment by mknoedel** [comment]
> Awesome! I love the idea of adding screenshots to docs. Much more useful. A bit more effort to keep up to date as things change, but I think it's worth it from a documentation perspective.
> 
> Wondering if we should make these images a bit larger?
> 
> https://github.com/JupiterOne/graph-microsoft-365/blob/de8eb28f8d3741249bd53528499460ade7f03e86/docs/jupiterone.md
> 
> Screen Shot 2021-02-10 at 2 37 28 PM

I'm ok with making these larger

**Comment by aiwilliams** [comment]
Is there another PR that will make the images larger?

**Comment by aiwilliams** [comment]
Actually, they seem large enough in their source, so I guess it will be a matter of the CSS on the deployment site.

**Comment by aiwilliams** [comment]
Looks like it can be controlled in the markdown: https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

```
- `![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | width=100)`
  - ![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png | width=100)

- `![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png =250x250)`
  - ![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png =250x250)

- `![](https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png)`  
  - Copy `<img>` in browser DevTools. Replace `![](url)` to `<img>`. Add width(and height) attr.
  - `<img src="https://camo.githubusercontent.com/..." data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />`
  - <img src="https://camo.githubusercontent.com/331400aee821efda2e36ee9b3bc8bce93b975109/68747470733a2f2f6779617a6f2e636f6d2f65623563353734316236613961313663363932313730613431613439633835382e706e67" alt="" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="200" height="400" />
  -
```

**Pull request merged**
